server:
  port: 80

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://127.0.0.1:3306/gxsx?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com/yxb/gxsx/entity
##    type-aliases-package: com\yxb\gxsx\entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#配置Mybatis-Plus
mybatis-plus:
  #配置扫描xml
  mapper-locations: classpath:mapper/*/*Mapper.xml
  #配置实体扫描类
  type-aliases-package: com.yxb.gxsx.entity
  #逻辑删除配置
#  global-config:
#    logic-delete-value: 1
#    logic-not-delete-value: 0
